# These are supported funding model platforms

github: [clxrityy] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://paypal.me/mjanglin?country.x=US&locale.x=en_US"]
